### ISSUE TITLE
possible GitHub Actions error

### ISSUE THREAD

**Issue by LucasHT22** [hack-club-brasil/v1#4]
https://brasil.hackclub.com/ it's not showing the same of https://hack-club-brasil.netlify.app/

**Comment by adrianoapj** [comment]
Opa, não tinha visto essa issue, mas isso é normal, porque o https://hack-club-brasil.netlify.app/ é um deploy que está com o Vitor e eu não tenho acesso. Até então continuávamos fazendo deploy lá, mas após uma atualização na versão mínima de uma biblioteca, parou de funcionar e mudamos
